### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by vivek2019meh** [Wovchena/text-detection-fots.pytorch#10]
I got gt in .txt file..but i think we need .mat file.
(datasets.py ,line-177)
how i can resolve that issue.?

**Comment by Wovchena** [comment]
The difference is in data set used: https://github.com/Wovchena/text-detection-fots.pytorch/blob/7abd5248c6bb696d5ae0084489e4ff0f66df66e2/train.py#L311
ICDAR provides `.txt` for ground truth and SynthText has `.mat`. So `datasets.SynthText` and `datasets.ICDAR2015` treat the provided path differently.

The solution is to uncomment `# icdar = datasets.ICDAR2015(args.train_folder, datasets.transform)` and remove `synth = datasets.SynthText(args.train_folder, datasets.transform)` to train on ICDAR.
