### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by liujiale1234** [Wovchena/text-detection-fots.pytorch#7]
My output is a .txt file with coordinates. How do I visualize it to a specific image?

**Comment by Wovchena** [comment]
There is a commented code https://github.com/Wovchena/text-detection-fots.pytorch/blob/d9c727a8defbd1c8022478ae798c907ccd2fa0b2/test.py#L41 visualizing the results.

**Comment by Wovchena** [comment]
Added a note about it: e973d4c9bd733d9e812ac5117570ee05ff37df40
